### PR TITLE
Add Binder files

### PR DESCRIPTION
**Pull request by jtpio**
Let's see if it's possible to get a Binder with this `postBuild` file.

### CODE REVIEW

**Comment by jtpio** [comment]
We'll also need a few more dependencies: https://github.com/marimeireles/pyls-memestra#for-a-development-environment

**Comment by jtpio** [comment]
Building at:

[Binder](https://mybinder.org/v2/gh/jtpio/pyls-memestra/postbuild)

**Comment by marimeireles** [comment]
Nice. Thanks a lot @jtpio can I do something here to help?

**Comment by jtpio** [comment]
Is there a sample file we could use to test? Then we could include it in the binder folder,

**Comment by marimeireles** [comment]
Yeah, there is the file under `tests`, do we have to have one specifically for binder or can we use this other one?

**Comment by jtpio** [comment]
We can use the same and open it automatically on start.

**Comment by jtpio** [comment]
It should be up at https://mybinder.org/v2/gh/jtpio/pyls-memestra/postbuild?urlpath=/lab/ now

**Comment by jtpio** [comment]
image

**Comment by jtpio** [comment]
Pushing some more changes so it's going to rebuild :)

**Comment by marimeireles** [comment]
Huh, that's not how it's working for me @jtpio 
For me all of the python-language-server plugins are showing up as if you have done `pip install  python-language-server[all]`... I think it might be because `conda install` is installing all of these plugins by default.
You don't have that? A lot of underlines under one word? It doesn't look like by your picture.

**Comment by marimeireles** [comment]
Okay, so I should wait for the rebuild and try again?

**Comment by jtpio** [comment]
Yes it's picking up the other hints (2 lines before a function declaration). The last commit should hopefully fix that.

**Comment by marimeireles** [comment]
Thanks Jeremy! :cherry_blossom:

**Pull request merged**
